//package com.mestero.network.firebase
//
//import com.google.firebase.firestore.DocumentReference
//import com.google.firebase.firestore.Query
//import com.google.firebase.firestore.QuerySnapshot
//import kotlinx.coroutines.flow.Flow
//
//interface FirestoreRepository {
//    suspend fun getDocument(collection: String, documentId: String): DocumentReference
//    suspend fun getDocuments(collection: String): QuerySnapshot
//    suspend fun addDocument(collection: String, data: Any): DocumentReference
//    suspend fun updateDocument(collection: String, documentId: String, data: Any)
//    suspend fun deleteDocument(collection: String, documentId: String)
//    suspend fun queryDocuments(collection: String, field: String, value: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrder(collection: String, field: String, value: Any, orderBy: String, limit: Long): QuerySnapshot
//    suspend fun queryDocumentsWithOrderDesc(collection: String, field: String, value: Any, orderBy: String, limit: Long): QuerySnapshot
//    suspend fun queryDocumentsWithOrderAndStartAfter(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderDescAndStartAfter(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderAndStartAfterAndEndBefore(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderDescAndStartAfterAndEndBefore(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderAndStartAfterAndEndBeforeAndWhereEqualTo(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderDescAndStartAfterAndEndBeforeAndWhereEqualTo(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThan(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderDescAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThan(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThan(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderDescAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThan(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThanAndWhereArrayContains(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any, whereArrayContainsField: String, whereArrayContainsValue: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderDescAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThanAndWhereArrayContains(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any, whereArrayContainsField: String, whereArrayContainsValue: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThanAndWhereArrayContainsAndWhereArrayContainsAny(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any, whereArrayContainsField: String, whereArrayContainsValue: Any, whereArrayContainsAnyField: String, whereArrayContainsAnyValue: List<Any>): QuerySnapshot
//    suspend fun queryDocumentsWithOrderDescAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThanAndWhereArrayContainsAndWhereArrayContainsAny(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any, whereArrayContainsField: String, whereArrayContainsValue: Any, whereArrayContainsAnyField: String, whereArrayContainsAnyValue: List<Any>): QuerySnapshot
//    suspend fun queryDocumentsWithOrderAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThanAndWhereArrayContainsAndWhereArrayContainsAnyAndWhereIn(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any, whereArrayContainsField: String, whereArrayContainsValue: Any, whereArrayContainsAnyField: String, whereArrayContainsAnyValue: List<Any>, whereInField: String, whereInValue: List<Any>): QuerySnapshot
//    suspend fun queryDocumentsWithOrderDescAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThanAndWhereArrayContainsAndWhereArrayContainsAnyAndWhereIn(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any, whereArrayContainsField: String, whereArrayContainsValue: Any, whereArrayContainsAnyField: String, whereArrayContainsAnyValue: List<Any>, whereInField: String, whereInValue: List<Any>): QuerySnapshot
//    suspend fun queryDocumentsWithOrderAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThanAndWhereArrayContainsAndWhereArrayContainsAnyAndWhereInAndWhereNotIn(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any, whereArrayContainsField: String, whereArrayContainsValue: Any, whereArrayContainsAnyField: String, whereArrayContainsAnyValue: List<Any>, whereInField: String, whereInValue: List<Any>, whereNotInField: String, whereNotInValue: List<Any>): QuerySnapshot
//    suspend fun queryDocumentsWithOrderDescAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThanAndWhereArrayContainsAndWhereArrayContainsAnyAndWhereInAndWhereNotIn(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any, whereArrayContainsField: String, whereArrayContainsValue: Any, whereArrayContainsAnyField: String, whereArrayContainsAnyValue: List<Any>, whereInField: String, whereInValue: List<Any>, whereNotInField: String, whereNotInValue: List<Any>): QuerySnapshot
//    suspend fun queryDocumentsWithOrderAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThanAndWhereArrayContainsAndWhereArrayContainsAnyAndWhereInAndWhereNotInAndWhereNotEqualTo(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any, whereArrayContainsField: String, whereArrayContainsValue: Any, whereArrayContainsAnyField: String, whereArrayContainsAnyValue: List<Any>, whereInField: String, whereInValue: List<Any>, whereNotInField: String, whereNotInValue: List<Any>, whereNotEqualToField: String, whereNotEqualToValue: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderDescAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThanAndWhereArrayContainsAndWhereArrayContainsAnyAndWhereInAndWhereNotInAndWhereNotEqualTo(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any, whereArrayContainsField: String, whereArrayContainsValue: Any, whereArrayContainsAnyField: String, whereArrayContainsAnyValue: List<Any>, whereInField: String, whereInValue: List<Any>, whereNotInField: String, whereNotInValue: List<Any>, whereNotEqualToField: String, whereNotEqualToValue: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThanAndWhereArrayContainsAndWhereArrayContainsAnyAndWhereInAndWhereNotInAndWhereNotEqualToAndWhereGreaterThanOrEqualTo(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any, whereArrayContainsField: String, whereArrayContainsValue: Any, whereArrayContainsAnyField: String, whereArrayContainsAnyValue: List<Any>, whereInField: String, whereInValue: List<Any>, whereNotInField: String, whereNotInValue: List<Any>, whereNotEqualToField: String, whereNotEqualToValue: Any, whereGreaterThanOrEqualToField: String, whereGreaterThanOrEqualToValue: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderDescAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThanAndWhereArrayContainsAndWhereArrayContainsAnyAndWhereInAndWhereNotInAndWhereNotEqualToAndWhereGreaterThanOrEqualTo(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any, whereArrayContainsField: String, whereArrayContainsValue: Any, whereArrayContainsAnyField: String, whereArrayContainsAnyValue: List<Any>, whereInField: String, whereInValue: List<Any>, whereNotInField: String, whereNotInValue: List<Any>, whereNotEqualToField: String, whereNotEqualToValue: Any, whereGreaterThanOrEqualToField: String, whereGreaterThanOrEqualToValue: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThanAndWhereArrayContainsAndWhereArrayContainsAnyAndWhereInAndWhereNotInAndWhereNotEqualToAndWhereGreaterThanOrEqualToAndWhereLessThanOrEqualTo(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any, whereArrayContainsField: String, whereArrayContainsValue: Any, whereArrayContainsAnyField: String, whereArrayContainsAnyValue: List<Any>, whereInField: String, whereInValue: List<Any>, whereNotInField: String, whereNotInValue: List<Any>, whereNotEqualToField: String, whereNotEqualToValue: Any, whereGreaterThanOrEqualToField: String, whereGreaterThanOrEqualToValue: Any, whereLessThanOrEqualToField: String, whereLessThanOrEqualToValue: Any): QuerySnapshot
//    suspend fun queryDocumentsWithOrderDescAndStartAfterAndEndBeforeAndWhereEqualToAndWhereGreaterThanAndWhereLessThanAndWhereArrayContainsAndWhereArrayContainsAnyAndWhereInAndWhereNotInAndWhereNotEqualToAndWhereGreaterThanOrEqualToAndWhereLessThanOrEqualTo(collection: String, field: String, value: Any, orderBy: String, limit: Long, startAfter: Any, endBefore: Any, whereField: String, whereValue: Any, whereGreaterThanField: String, whereGreaterThanValue: Any, whereLessThanField: String, whereLessThanValue: Any, whereArrayContainsField: String, whereArrayContainsValue: Any, whereArrayContainsAnyField: String, whereArrayContainsAnyValue: List<Any>, whereInField: String, whereInValue: List<Any>, whereNotInField: String, whereNotInValue: List<Any>, whereNotEqualToField: String, whereNotEqualToValue: Any, whereGreaterThanOrEqualToField: String, whereGreaterThanOrEqualToValue: Any, whereLessThanOrEqualToField: String, whereLessThanOrEqualToValue: Any): QuerySnapshot
//}